---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: kinoite-nvidia-custom
# description will be included in the image's metadata
description: jhuang's custom kinoite OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/blue-build/base-images/fedora-kinoite-nvidia-open
image-version: 43 # latest is also supported if you want new updates ASAP

platforms:
  - linux/amd64

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /
      - source: skel
        destination: /etc/skel # copies files/skel/* into /etc/skel, which is the default skeleton directory for new users

  - type: bling
    install:
      - rpmfusion

  - type: dnf
    repos:
      copr:
        - avengemedia/dms
        - avengemedia/danklinux
    install:
      packages:
        - git
        - zsh
        - fastfetch
        - stow
        - btop
        - virt-manager
        - cava
        - niri
        - kitty
        - cmatrix
        - wl-clipboard
        - qt6-qtmultimedia
        - quickshell
        - material-symbols-fonts
        - matugen
        - dms
        - cliphist
        - dgop
        - danksearch
      exclude:
        - alacritty
        - waybar
        - fuzzel
        - swaylock
    remove:
      packages:
        # "firefox" is the main package, "firefox-langpacks" is a dependency
        - firefox
        - firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)

  - type: default-flatpaks
    configurations:
      - notify: true # Send notification after install/uninstall is finished (true/false)
        scope: system
        # If no repo information is specified, Flathub will be used by default
        install: # system flatpaks we want all users to have and not remove
          - com.google.Chrome
          - org.gnome.Loupe
          - io.mpv.Mpv
          - com.visualstudio.code
          - org.telegram.desktop
      - scope: user # Also add Flathub user repo, but no user packages

  - type: fonts
    fonts:
      nerd-fonts:
        - UbuntuSans
        - Hermit
        - CosmicShannsMono
        - ProggyClean
        - JetBrainsMono
        - NerdFontsSymbolsOnly
      google-fonts:
        - Roboto
        - Open Sans
        - Inter
      url-fonts:
        - name: Maple Mono NF CN
          url: 

  - type: systemd
    # system:
    #   disabled:
    user:
      enabled:
        - dms.service

  - type: script
    scripts:
      - |
        # Equvalent to `systemctl --user add-wants niri.service dms`
        DEST_DIR="/usr/lib/systemd/user/niri.service.wants"
        mkdir -p "$DEST_DIR"
        ln -sf "../dms.service" "$DEST_DIR/dms.service"

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
